repos:
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.2
    hooks:
      - id: bandit
        args: ["--recursive", "--exclude", ".venv, .coverage, .pytest_cache", "--skip", "B101"]
        verbose: true

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: [ "--ignore-missing-imports", "--scripts-are-modules" ]
        verbose: true

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.3
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
